### ISSUE TITLE
redirect() after output

### ISSUE THREAD

**Issue by mudrd8mz** [m-schwabe/local_bs_badge_ladder#3]
When saving the Course badge ladder form, debugging message is displayed:

```
You should really redirect before you start page output

    line 889 of /lib/outputrenderers.php: call to debugging()
    line 2674 of /lib/weblib.php: call to core_renderer->redirect_message()
    line 266 of /local/bs_badge_ladder/index.php: call to redirect()

Error output, so disabling automatic redirect.
```

Make sure to have full DEBUG_DEVELOPER enable to spot these things while developing your plugins.

**Comment by m-schwabe** [comment]
This is not an error message, it's a warning message in debugging mode. It will disappear when switching debugging mode off.

**Comment by mudrd8mz** [comment]
I am well aware of that. But switching debugging mode off is not the way to fix incorrectly written code.
